# See answer https://stackoverflow.com/a/44054333 of
# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages

matrix:
    include:
        -   language: go
            go:
                - "1.11.x"
            before_install:
                - go get golang.org/x/tools/cmd/goimports
                - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1

            before_script:
                - cd jenkins/webhook-proxy
            script:
                - env GO111MODULE=on make lint
                - env GO111MODULE=on make test
        -   language: go
            go:
                - "1.17.x"
            before_install:
                - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
                - go get golang.org/x/tools/cmd/goimports
                - wget https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
                - tar -xzvf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
                - export PATH=$PATH:$PWD/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit
                - sudo sed -i "s/\DOCKER_OPTS=\"/DOCKER_OPTS=\"--insecure-registry=172.16.0.0\/12 /g" /etc/default/docker
                - sudo cat /etc/default/docker
                - sudo service docker restart
                - oc cluster up
            before_script:
                - cd create-projects
            script:
                - env GO111MODULE=on make lint
                - env GO111MODULE=on make test
