---
atlassian_confluence_version: 6.1.3
# installation directory
atlassian_confluence_installation_dir: /opt/atlassian/confluence

# data directory of confluence
# see https://confluence.atlassian.com/doc/confluence-home-and-other-important-directories-590259707.html
atlassian_confluence_home: /srv/atlassian/confluence

# is this an upgrade of an existing installation?
atlassian_confluence_upgrade: false

# the confluence jdbc connection url
atlassian_confluence_jdbc_url: "jdbc:postgresql://{{postgresql_host}}:{{postgresql_port}}/confluence"
atlassian_confluence_jvm_mem: 1024m