---
- name: load var from file
  slurp:
    src: "{{ target_path }}"
  register: imported_var

- debug:
    msg: "{{ imported_var.content|b64decode|from_json }}"

- name: append more key/values
  set_fact:
    imported_var: "{{ imported_var.content|b64decode|from_json | default([]) | combine( additional_json  ) }}"

- debug:
    var: imported_var

- name: write var to file
  copy: 
    content: "{{ imported_var | to_nice_json }}" 
    dest: "{{ target_path }}"

