---
- hosts: localhost
  tasks:
  - name: "install additional packages"
    package:
      name: ['vim','python2-pip','tmux', 'tig', 'python-psycopg2']
    become: True

#  - name: "upgrade pip"
#    pip:
#      name: pip
#      extra_args: --upgrade
#    become: True

  - name: "install python libraries for postgres"
    pip:
      name: psycopg2-binary
    become: True

  - name: "install python libraries for aws"
    pip:
      name: ['boto', 'awscli', ]
    become: True
    when: environment_enable_aws == true

  - name: install centos pgdg
    yum:
      name: https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-3.noarch.rpm
      state: present
    become: true
    when: "'CentOS' in ansible_distribution"

  - name: install redhat pgdg
    yum:
      name: https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-7-x86_64/pgdg-redhat94-9.4-3.noarch.rpm
      state: present
    become: true
    when: "'RedHat' in ansible_distribution"

  - name: remove postgresql 9.2 client
    package:
      name: postgresql
      state: absent
    become: True

  - name: add postgresql94 client
    package:
      name: postgresql94
    become: true

  - name: install git prompt
    git:
      repo: https://github.com/magicmonty/bash-git-prompt.git
      dest: "{{ ansible_user_dir }}/.bash-git-prompt"

  - name: install bashrc
    template:
      src: templates/bashrc_controller.j2
      dest: "{{ ansible_user_dir }}/.bashrc"

