---
- hosts: "{{ target_hosts | default('tag_hostgroup_bitbucket_dev') }}"
  pre_tasks:
  - include_tasks: common/common-tasks.yml
  roles:
  - role: geerlingguy.git
    become: true
    git_install_from_source: true
    git_install_from_source_force_update: true
  - role: local.atlassian_bitbucket
    atlassian_bitbucket_jdbc_password: "{{bitbucket_database_user_password}}"
