---
- hosts: "{{ target_hosts | default('tag_hostgroup_confluence_dev') }}"
  roles:
  - role: local.atlassian_confluence
    tags: confluence
    atlassian_confluence_upgrade: true
    atlassian_confluence_version: 6.9.1
