---
- hosts: tag_hostgroup_crowd
  tasks:
  - name: "download cleito connector"
    delegate_to: 127.0.0.1
    get_url:
      url: https://www.cleito.com/products/odcc/downloads/{{cleito_basename}}.zip
      dest: "{{cleito_download_dir}}"
    become: True

  - name: ensure unarchive programs are installed
    delegate_to: 127.0.0.1
    package:
      name: unzip
      use: yum
    become: True

  - name: extract downloaded o365 connector
    delegate_to: 127.0.0.1
    unarchive:
      creates: "{{cleito_download_dir}}/{{cleito_basename}}"
      src: "{{cleito_download_dir}}/{{cleito_basename}}.zip"
      dest: "{{cleito_download_dir}}"
    become: True

# see https://www.cleito.com/products/odcc/documentation/#step2
  - name: copy plugin libraries
    copy:
      src: "{{cleito_download_dir}}/{{cleito_basename}}/lib/"
      dest: "{{atlassian_crowd_dir}}/crowd-webapp/WEB-INF/lib"
      owner: crowd
    become: True
  - name: copy extra-lib
    copy:
      src: "{{cleito_download_dir}}/{{cleito_basename}}/extra-libs/"
      dest: "{{atlassian_crowd_dir}}/crowd-webapp/WEB-INF/lib"
      owner: crowd
    become: True

  - name: config log4j for cleito
    blockinfile:
      block: |
        ### CLEITO ODCC ###
        log4j.logger.com.cleito=ALL
        log4j.logger.javax.mail=WARN
        log4j.logger.com.sun.mail.imap=WARN
      dest: "{{atlassian_crowd_dir}}/crowd-webapp/WEB-INF/classes/log4j.properties"
      owner: crowd
    become: True
    notify: restart crowd
  handlers:
  - name: "restart crowd"
    systemd:
      name: crowd
      state: restarted
    become: True
  vars:
    atlassian_basedir: /opt/atlassian
    atlassian_crowd_dir: "{{atlassian_basedir}}/atlassian-crowd-2.11.2"
    cleito_basename: CLEITO-ODCC-1.1
    cleito_download_dir: /tmp
