apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: nexus3
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: nexus3
    name: nexus3
  spec:
    lookupPolicy:
      local: false
