apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: nexus3
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ebs
    creationTimestamp: null
    labels:
      app: nexus3
    name: nexus3-pv
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50G
