apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: nexus3
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ${STORAGE_CLASS_DATA}
      volume.beta.kubernetes.io/storage-provisioner: ${STORAGE_PROVISIONER}
    creationTimestamp: null
    labels:
      app: nexus3
    name: nexus-data-extended
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${NEXUS_DATA_CAPACITY}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ${STORAGE_CLASS_BACKUP}
      volume.beta.kubernetes.io/storage-provisioner: ${STORAGE_PROVISIONER}
    creationTimestamp: null
    labels:
      app: nexus3
    name: nexus-db-backup
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${NEXUS_BACKUP_CAPACITY}
parameters:
# the storage class provisioner
# for AWS kubernetes.io/aws-ebs
# leave empty for local (e.g. vagrant) deployments
- name: STORAGE_PROVISIONER
# storage class for data
# for AWS gp2
# leave empty for local (e.g. vagrant) deployments
- name: STORAGE_CLASS_DATA
# storage class for data backup
# for AWS gp2-encrypted
# leave empty for local (e.g. vagrant) deployments
- name: STORAGE_CLASS_BACKUP
- name: NEXUS_DATA_CAPACITY
  value: 60Gi
- name: NEXUS_BACKUP_CAPACITY
  value: 10Gi
