apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ods-provisioning-app
    name: ods-provisioning-app
  spec:
    lookupPolicy:
      local: false
