apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: cd-user-token
    labels:
      app: shared-services
  type: kubernetes.io/basic-auth
  data:
    username: ${CD_USER_ID_B64}
    password: ${CD_USER_PWD_B64}
parameters:
- name: CD_USER_ID_B64
  description: cd_user username (base64 encoded)
  required: true
- name: CD_USER_PWD_B64
  description: cd_user password (base64 encoded)
  required: true
